#!/bin/sh

vendor=
lsb_release -si 2>/dev/null|grep -qi debian && vendor=debian
lsb_release -si 2>/dev/null|grep -qi ubuntu && vendor=ubuntu
lsb_release -si 2>/dev/null|grep -qi devuan && vendor=devuan
lsb_release -si 2>/dev/null|grep -qi raspbian && vendor=raspbian
dist=`lsb_release -sc 2>/dev/null`

# Linux Mint is based on Ubuntu, Linux Mint Debain Edition is based on Debian
if [ `lsb_release -si|tr A-Z a-z` = 'linuxmint' ]; then
	vendor=`grep ID_LIKE /etc/os-release | cut -d= -f2` # required for older Mint verions
   grep -q UBUNTU_CODENAME /etc/os-release && vendor=ubuntu
   grep -q DEBIAN_CODENAME /etc/os-release && vendor=debian
	dist=`grep -i "$vendor"_codename /etc/os-release | cut -d= -f2`
fi

if [ -z "$vendor" -o -z "$dist" ]; then
	echo
	echo
	echo WARNING:
	echo
	echo "  Can't detect OS distributor or codename (based on lsb_release output)"
	echo "  Adjust /etc/apt/sources.list.d/netxms.list and run \"apt update\""
	echo
	echo
else
	sed -i "s/VENDOR/$vendor/" /etc/apt/sources.list.d/netxms.list
	sed -i "s/DIST/$dist/" /etc/apt/sources.list.d/netxms.list
fi
exit 0
